### ISSUE TITLE
GetStringDescriptorASCII broken on Raspbian

### ISSUE THREAD

**Issue by matthewrankin** [gotmc/libusb#2]
`GetStringDescriptorASCII()` on a Raspberry Pi running Raspbian Jessie Lite doesn't work.

**Comment by rojer** [comment]
getting the same on Ubuntu 16.04
the root cause seems to be handling of libusb_get_string_descriptor_ascii's return value ([here](https://github.com/gotmc/libusb/blob/653c9b36c0be35324f6b065c80d6129cccb46b99/handle.go#L57)).
looking at C code, it seems that return value in case of error will be negative, just like in the case of get_string_descriptor and should be treated in [the same way](https://github.com/gotmc/libusb/blob/653c9b36c0be35324f6b065c80d6129cccb46b99/handle.go#L34).

**Comment by matthewrankin** [comment]
@rojer According to the [cgo][] documentation:

> Any C function (even void functions) may be called in a multiple assignment context to retrieve both the return value (if any) and the C errno variable as an error (use _ to skip the result value if the function returns void). For example:
>
> `n, err = C.sqrt(-1)`
> `_, err := C.voidFunc()`
> `var n, err = C.sqrt(1)`

I need to do a little research and experimentation.

[cgo]: https://golang.org/cmd/cgo/

**Comment by matthewrankin** [comment]
Turns out the current code is reading bytes, but also returning a "resource temporarily unavailable" error. This test was performed on a Raspberry Pi 3 running Raspbian Jessie Lite with an MCC DAQ USB-1608FS-Plus attached.

When I perform the same test on my MacBook Pro with an MCC DAQ USB-1608FS-Plus, the error is nil instead of "resource temporarily unavailable". Not sure why the MBP is giving a different answer than the RPi3.

**Comment by matthewrankin** [comment]
When reading on the RPi3, when `bytesRead = -2` the error is nil, so using two returns in the function ins't working as I had thought.
